language: node_js
node_js:
  - "4.0"
before_script:
  - npm install -g bower
  - bower install
  - npm install --dev
script:
  - echo 'Start Travis CI Integration Test'
  - node app.js &
  - sleep 5
  - node_modules/karma/bin/karma start karma.conf.js --single-run
  # - jasmine-node ./test/api
after_success:
  - echo 'Travis CI Integration Test Success!'
