language: node_js
node_js:
  - "4.0"
before_script:
  - npm install -g bower
  - bower install
  - npm install --dev
script:
  - node_modules/karma/bin/karma start karma.conf.js --single-run
after_success:
  - echo 'Success!'
