language: node_js
node_js:
  - "4.0"
before_script:
  - npm install -g bower
  - bower install
  - npm install --dev
script:
  - ./scripts/test
after_success:
  - echo 'Travis CI Integration Test Success!'
