# Test script inspired by http://blog.apiary.io/2013/10/17/How-to-test-api-with-api-blueprint-and-dredd/

language: node_js
node_js:
  - "4.0"
before_script:
  - npm install -g bower
  - bower install
  - npm install --dev
script:
  - ./scripts/test
after_success:
  - echo 'Travis CI Integration Test Success!'
